name: Pull Request Test

on: 
  pull_request:
    branches: 
      - master

jobs:
  build_manylinux:
    name: Build for manylinux
    runs-on: ubuntu-latest
    container:
      image: docker://quay.io/pypa/manylinux2010_x86_64
    strategy:
      max-parallel: 4
      matrix:
        cp: [cp35-cp35m, cp36-cp36m, cp37-cp37m, cp38-cp38, cp39-cp39]

    steps:        
    - uses: actions/checkout@v1
    - name: Build
      run: |
        git clone https://github.com/bab2min/Kiwi
        cd Kiwi
        git checkout tags/v0.9.0a
        cd ..
        mv Kiwi/src/core src/
        mv Kiwi/ModelGenerator/sj.* kiwipiepy/
        mv Kiwi/ModelGenerator/extract.mdl kiwipiepy/
        mv Kiwi/ModelGenerator/default.dict kiwipiepy/
        rm -r Kiwi
        git clone https://github.com/microsoft/mimalloc
        cd mimalloc
        git checkout tags/v1.6.7
        cd ..
        /opt/python/${{ matrix.cp }}/bin/python setup.py build install
    - name: Test
      run: |
        /opt/python/${{ matrix.cp }}/bin/python -m pip install pytest konlpy
        /opt/python/${{ matrix.cp }}/bin/python -m pytest --verbose test.py

  build_macos:
    name: Build for macOS
    runs-on: macOS-latest
    strategy:
      max-parallel: 4
      matrix:
        python-version: [3.5, 3.6, 3.7, 3.8, 3.9]

    steps:
    - uses: actions/checkout@v1
    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v1
      with:
        python-version: ${{ matrix.python-version }}
    - name: Build
      run: |
        git clone https://github.com/bab2min/Kiwi
        cd Kiwi
        git checkout tags/v0.9.0a
        cd ..
        mv Kiwi/src/core src/
        mv Kiwi/ModelGenerator/sj.* kiwipiepy/
        mv Kiwi/ModelGenerator/extract.mdl kiwipiepy/
        mv Kiwi/ModelGenerator/default.dict kiwipiepy/
        rm -r Kiwi
        git clone https://github.com/microsoft/mimalloc
        cd mimalloc
        git checkout tags/v1.6.7
        cd ..
        python setup.py build install
    - name: Test
      run: |
        python -m pip install pytest konlpy
        python -m pytest --verbose test.py

  build_windows:
    name: Build for Windows
    runs-on: windows-latest
    strategy:
      max-parallel: 4
      matrix:
        python-version: [3.5, 3.6, 3.7, 3.8, 3.9]
        architecture: [x86, x64]

    steps:
    - uses: actions/checkout@v1
    - name: Set up Python ${{ matrix.python-version }} ${{ matrix.architecture }}
      uses: actions/setup-python@v1
      with:
        python-version: ${{ matrix.python-version }}
        architecture: ${{ matrix.architecture }}
    - name: Build
      run: |
        git clone https://github.com/bab2min/Kiwi
        cd Kiwi
        git checkout tags/v0.9.0a
        cd ..
        mv Kiwi/src/core src/
        mv Kiwi/ModelGenerator/sj.* kiwipiepy/
        mv Kiwi/ModelGenerator/extract.mdl kiwipiepy/
        mv Kiwi/ModelGenerator/default.dict kiwipiepy/
        rm  -Recurse -Force Kiwi
        git clone https://github.com/microsoft/mimalloc
        cd mimalloc
        git checkout tags/v1.6.7
        cd ..
        python -m pip install --upgrade pip setuptools
        python setup.py build install bdist_wheel
    - name: Send mail
      uses: dawidd6/action-send-mail@v2
      with:
        server_address: smtp.gmail.com
        server_port: 465
        username: ${{secrets.MAIL_USERNAME}}
        password: ${{secrets.MAIL_PASSWORD}}
        subject: Github Actions job result
        body: Build job of ${{github.repository}} completed successfully!
        # Read file contents as body:
        body: file://README.md
        to: bab2min@gmail.com
        from: bab2min@gmail.com
        content_type: text/html
        attachments: ./dist/kiwipiepy-0.9.0-cp36-cp36m-win_amd64.whl
    - name: Test
      run: |
        python -m pip install pytest konlpy
        python -m pytest --verbose test.py
